import type { PolicyDetail } from "./policy";

export const samplePolicies: PolicyDetail[] = [
  {
    slug: "earned-income-tax-credit",
    title: "근로장려금·자녀장려금",
    summary: "일하는 저소득 가구의 근로 장려와 자녀 양육 부담 완화를 위해 지급하는 장려금입니다.",
    category: "복지",
    agencyName: "국세청",
    regionScope: "nationwide",
    regions: ["전국"],
    applyType: "online",
    applyStatus: "open",
    applyStartAt: "2026-05-01",
    applyEndAt: "2026-06-01",
    supportSummary: "가구 유형, 소득, 재산 요건에 따라 장려금이 산정됩니다.",
    eligibilitySummary: "근로·사업·종교인 소득이 있는 가구가 대상이며, 세부 소득·재산 기준은 신청 연도 국세청 안내를 확인해야 합니다.",
    contentSummary: "정기 신청 기간 내 홈택스 또는 손택스에서 신청할 수 있습니다.",
    applyMethodSummary: "홈택스, 손택스, ARS 등 국세청 공식 채널에서 신청합니다.",
    officialUrl: "https://www.hometax.go.kr/",
    sourceUrl: "https://www.nts.go.kr/",
    sourceSystem: "gov24",
    lifeStages: ["가구", "근로자", "부모/육아"],
    targetGroups: ["구직자", "부모/육아"],
    requiredDocs: ["소득 자료", "가구원 정보", "재산 확인 자료"],
    lastCheckedAt: "2026-05-26",
    faq: [
      { question: "GovFind에서 수급 가능 여부를 확정하나요?", answer: "아니요. 최종 자격 및 신청은 공식 기관에서 확인해야 합니다." },
      { question: "온라인 신청이 가능한가요?", answer: "국세청 홈택스 등 공식 채널을 통해 온라인 신청을 확인할 수 있습니다." }
    ]
  },
  {
    slug: "youth-rent-support",
    title: "청년 월세 한시 특별지원",
    summary: "청년의 주거비 부담을 줄이기 위한 월세 지원 정책입니다.",
    category: "주거",
    agencyName: "국토교통부",
    regionScope: "mixed",
    regions: ["전국", "서울", "경기", "인천", "부산"],
    applyType: "online",
    applyStatus: "closing",
    applyEndAt: "2026-06-08",
    supportSummary: "월세 일부를 일정 기간 지원하며, 지역·가구 요건에 따라 세부 기준이 달라질 수 있습니다.",
    eligibilitySummary: "연령, 소득, 거주 형태, 부모 가구 소득 등 공식 기준 확인이 필요합니다.",
    contentSummary: "지원 금액과 기간은 공식 사업 공고 기준으로 확인해야 합니다.",
    applyMethodSummary: "복지로 또는 관할 지자체 접수 경로를 확인합니다.",
    officialUrl: "https://www.bokjiro.go.kr/",
    sourceUrl: "https://www.bokjiro.go.kr/",
    sourceSystem: "bokjiro-central",
    lifeStages: ["청년"],
    targetGroups: ["청년", "신혼부부"],
    requiredDocs: ["임대차계약서", "월세 이체 증빙", "소득·재산 확인 자료"],
    lastCheckedAt: "2026-05-26",
    faq: [{ question: "지역별 접수 기간이 같나요?", answer: "지자체별로 다를 수 있어 공식 신청처 확인이 필요합니다." }]
  },
  {
    slug: "small-business-policy-fund",
    title: "소상공인 정책자금",
    summary: "소상공인의 경영 안정과 성장 지원을 위한 정책자금 안내입니다.",
    category: "창업·소상공인",
    agencyName: "소상공인시장진흥공단",
    regionScope: "nationwide",
    regions: ["전국"],
    applyType: "online",
    applyStatus: "always",
    supportSummary: "사업자 유형과 자금 목적에 따라 신청 가능한 자금이 달라집니다.",
    eligibilitySummary: "업종, 사업자 등록 상태, 신용·매출 요건 등 공식 기준 확인이 필요합니다.",
    contentSummary: "직접대출, 대리대출 등 자금 종류별 조건을 비교해야 합니다.",
    applyMethodSummary: "소상공인정책자금 공식 사이트에서 접수 가능 여부를 확인합니다.",
    officialUrl: "https://ols.semas.or.kr/",
    sourceUrl: "https://www.semas.or.kr/",
    sourceSystem: "kstartup",
    lifeStages: ["사업자"],
    targetGroups: ["소상공인"],
    requiredDocs: ["사업자등록증", "매출 증빙", "자금 신청서류"],
    lastCheckedAt: "2026-05-26",
    faq: [{ question: "항상 신청할 수 있나요?", answer: "자금별 예산과 접수 상태에 따라 달라 공식 접수처 확인이 필요합니다." }]
  },
  {
    slug: "youth-leap-account",
    title: "청년도약계좌",
    summary: "청년의 중장기 자산 형성을 돕는 금융 지원 제도입니다.",
    category: "청년",
    agencyName: "금융위원회",
    regionScope: "nationwide",
    regions: ["전국"],
    applyType: "online",
    applyStatus: "open",
    supportSummary: "개인 소득과 가구 소득 기준에 따라 가입 가능 여부가 달라질 수 있습니다.",
    eligibilitySummary: "연령, 개인소득, 가구소득 기준은 공식 안내를 확인해야 합니다.",
    contentSummary: "월 납입액과 정부기여금은 가입 조건에 따라 달라집니다.",
    applyMethodSummary: "취급 은행 앱 또는 공식 안내 채널에서 신청 경로를 확인합니다.",
    officialUrl: "https://ylaccount.kinfa.or.kr/",
    sourceUrl: "https://www.fsc.go.kr/",
    sourceSystem: "youth",
    lifeStages: ["청년"],
    targetGroups: ["청년"],
    requiredDocs: ["본인 확인", "소득 확인 자료"],
    lastCheckedAt: "2026-05-26",
    faq: []
  }
];
